version: 1.0
disable_existing_loggers: true

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout


loggers:
  uvicorn:
    error:
      propagate: no

root:
  level: NOTSET
  handlers: [console]
  propagate: no