apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: pimenovdv/books-classifier:0.2.13
          imagePullPolicy: Always
          command: ["uvicorn", "books_classifier.app.main:app_factory", "--factory", "--host", "0.0.0.0", "--port", "9999"]
          ports:
            - containerPort: 9999
  selector:
    matchLabels:
      app: backend-app