apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: sbugallo/mlflow-server:1.20.2
        imagePullPolicy: Always
        args:
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service/$(POSTGRES_DB)
        - --default-artifact-root=s3://books-classifier-mlflow/models/
        - --workers=2
        env:
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: s3://books-classifier-mlflow/models/
        - name: MLFLOW_ARTIFACTS_DESTINATION
          value: s3://books-classifier-mlflow/models/
        - name: MLFLOW_S3_ENDPOINT_URL
          value: https://storage.yandexcloud.net
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key-id
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-access-key
              key: aws-secret-access-key
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: aws-creds
          mountPath: "/root/.aws/"
          readOnly: true
      volumes:
      - name: aws-creds
        secret:
          secretName: aws-credentials
          items:
          - key: credentials
            path: credentials